services:
  bookstore-web:
    image: acme/bookstore-web:latest
    container_name: bookstore-web
    hostname: bookstore-web
    build:
      context: ../../
      dockerfile: src/Acme.BookStore.Web/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=bb3f5119-e73d-4754-bfec-9ecea97bdc8f
      - App__SelfUrl=https://localhost:44353
      - App__HealthCheckUrl=http://bookstore-web:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://bookstore-web:8080      
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=BookStore;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    ports:
      - "44353:8081"
    depends_on:
      sql-server:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network

  

  
  db-migrator:
    image: acme/bookstore-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/Acme.BookStore.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__BookStore_Web__RootUrl=https://localhost:44353
      - OpenIddict__Applications__BookStore_Swagger__RootUrl=https://localhost:44341
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=BookStore;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    restart: on-failure
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/azure-sql-edge:1.0.7
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -C -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqldata:
    name: bookstore_sqldata
networks:
  abp-network:
    name: bookstore-network
    driver: bridge